name: Employee Management CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: april1993/testing

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check Node.js
        run: node --version

      - name: Check npm
        run: npm --version

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |


deploy:

    needs: build-and-test

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to AWS EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

        run: |

          echo "$EC2_SSH_KEY" > private_key

          chmod 600 private_key

          ssh \
            -o StrictHostKeyChecking=no \
            -i private_key \
            $EC2_USERNAME@$EC2_HOST \
            "
              cd ~/employee &&
              export IMAGE_TAG=${{ github.sha }} &&
              docker compose pull app &&
              docker compose up -d app
            "

          rm -f private_key
        
          docker push \
            $IMAGE_NAME:${{ github.sha }}
